/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-26 17:27:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/meetingroommanagement/css/style.css\">\n");
      out.write("    <title>Admin | HMeets</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"page-container\">\n");
      out.write("    <header>\n");
      out.write("        <!-- Navbar -->\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-dark\" style=\"height: 8vh\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- Logo -->\n");
      out.write("                <img src=\"/meetingroommanagement/resources/images/logo.png\" height=\"30\" alt=\"\" />\n");
      out.write("                <h4 class=\"text-white ms-4 my-auto\">HMeets</h4>\n");
      out.write("                <!-- Logo -->\n");
      out.write("\n");
      out.write("                <!-- Menu button -->\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-mdb-toggle=\"collapse\" data-mdb-target=\"#navbarButtons\" aria-controls=\"navbarButtons\" aria-expanded=\"true\" aria-label=\"Toggle navigation\">\n");
      out.write("                    <img src=\"/meetingroommanagement/resources/images/icon_menu.png\" height=\"22\" alt=\"\" class=\"me-1\" />\n");
      out.write("                </button>\n");
      out.write("                <!-- Menu button -->\n");
      out.write("\n");
      out.write("                <!-- Nav Items -->\n");
      out.write("                <div class=\"collapse navbar-collapse align-items-center\" id=\"navbarButtons\">\n");
      out.write("                    <div class=\"me-auto\"></div>\n");
      out.write("                    <!-- <small class=\"text-info me-4\">Link</small> -->\n");
      out.write("                    <ul class=\"align-nav-item\">\n");
      out.write("                        <img src=\"/meetingroommanagement/resources/images/icon_user.png\" height=\"16\" alt=\"\" class=\"me-1\" />\n");
      out.write("                        <small class=\"text-white me-4\">Hi! Amit Kumar</small>\n");
      out.write("                    </ul>\n");
      out.write("                    <ul class=\"align-nav-item\">\n");
      out.write("                        <a href=\"login?op=logout\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-outline-info\" data-mdb-ripple-color=\"dark\">\n");
      out.write("                                Logout\n");
      out.write("                            </button>\n");
      out.write("                        </a>\n");
      out.write("                    </ul>\n");
      out.write("                    <!-- </div> -->\n");
      out.write("                </div>\n");
      out.write("                <!-- Nav Items -->\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <!-- Navbar -->\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <main id=\"content-wrap\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row d-flex justify-content-center align-items-center h-100\">\n");
      out.write("                <div class=\"col-9 col-sm-8 col-md-9 col-lg-6 col-xl-4 offset-xl-1\">\n");
      out.write("                    <!--Welcome Text-->\n");
      out.write("                    <div class=\"d-flex flex-row align-items-center justify-content-center justify-content-lg-start\">\n");
      out.write("                        <h3 class=\"text-muted\">Welcome to</h3><br>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <h1 class=\"text-center lead d-flex flex-row align-items-center justify-content-center justify-content-lg-start\">\n");
      out.write("                            Meeting Room Management</h1>\n");
      out.write("                    </div>\n");
      out.write("                    <!--/ Welcome Text-->\n");
      out.write("\n");
      out.write("                    <!--User Details-->\n");
      out.write("                    <div class=\"card mt-5 mb-3\" style=\"border-radius: .5rem;\">\n");
      out.write("                        <div class=\"row g-0\">\n");
      out.write("                            <div class=\"col-md-4 gradient-custom d-flex flex-row align-items-center justify-content-center\" style=\"border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;\">\n");
      out.write("                                <img src=\"/meetingroommanagement/resources/images/img_user_card.png\" alt=\"avatar\" class=\"rounded-circle img-fluid py-4 p-3\" style=\"width: 150px;\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-8\">\n");
      out.write("                                <div class=\"user-card-body px-4 py-2\">\n");
      out.write("                                    <h5 class=\"my-3\">Amit Kumar</h5>\n");
      out.write("                                    <hr class=\"my-4\">\n");
      out.write("                                    <div class=\"col-12 mb-1\">\n");
      out.write("                                        <h6>Email</h6>\n");
      out.write("                                        <p class=\"text-muted\">amit.kumar@hscc.co.in</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <hr class=\"mt-4\">\n");
      out.write("                                    <div class=\"col-12 mb-1\">\n");
      out.write("                                        <h6>Last Login</h6>\n");
      out.write("                                        <p class=\"text-muted\">24-October-2021, 9:00PM</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!--/ User Details-->\n");
      out.write("\n");
      out.write("                    <!--Action Buttons-->\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <button type=\"button\" class=\"btn\" id=\"btnadminoutline\">\n");
      out.write("                                Add New Room\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <button type=\" button\" class=\"btn\" id=\"btnadmin\">Edit Room</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!--/ Action Buttons-->\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <!--Background picture-->\n");
      out.write("                <div class=\"col-9 col-sm-6 col-md-6 col-lg-6 col-xl-5\">\n");
      out.write("                    <img src=\"/meetingroommanagement/resources/images/bg_admin.png\" class=\"img-fluid\" alt=\"Login\">\n");
      out.write("                </div>\n");
      out.write("                <!--Background picture-->\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    <!--Footer-->\n");
      out.write("    <footer id=\"footer\">\n");
      out.write("        <div>\n");
      out.write("            <hr class=\"my-2\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footer-copyright d-flex align-items-center justify-content-center\">\n");
      out.write("            © 2021 Copyright: HSCC Meettings\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("    <!--/.Footer-->\n");
      out.write("\n");
      out.write("    <!--scripts-->\n");
      out.write("    <script src=\"/meetingroommanagement/scripts/scripts.js\"></script>\n");
      out.write("    <!--scripts-->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
