/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-26 17:10:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hsbc.meets.entity.User;
import com.hsbc.meets.entity.Meeting;
import java.util.List;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/home/alan/Documents/HSBC/codefury/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/meetingroommanagement/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1632582023000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hsbc.meets.entity.Meeting");
    _jspx_imports_classes.add("com.hsbc.meets.entity.User");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fe_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fe_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fe_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/meetingroommanagement/css/style.css\">\n");
      out.write("    <title>Member | HMeets</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"page-container\">\n");

    User user = (User)request.getSession().getAttribute("user");
    pageContext.setAttribute("user", user); 
    
    List<Meeting> upcoming = (List<Meeting>) request.getAttribute("upcoming");
    pageContext.setAttribute("upcoming", upcoming);
    
    List<Meeting> recent = (List<Meeting>) request.getAttribute("recent");
    pageContext.setAttribute("recent", recent);
    

      out.write("\n");
      out.write("    <header>\n");
      out.write("        <!-- Navbar -->\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-dark\" style=\"height: 8vh\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <!-- Logo -->\n");
      out.write("                <img src=\"/meetingroommanagement/resources/images/logo.png\" height=\"30\" alt=\"\" />\n");
      out.write("                <h4 class=\"text-white ms-4 my-auto\">HMeets</h4>\n");
      out.write("                <!-- Logo -->\n");
      out.write("\n");
      out.write("                <!-- Menu button -->\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-mdb-toggle=\"collapse\" data-mdb-target=\"#navbarButtons\" aria-controls=\"navbarButtons\" aria-expanded=\"true\" aria-label=\"Toggle navigation\">\n");
      out.write("                    <img src=\"/meetingroommanagement/resources/images/icon_menu.png\" height=\"22\" alt=\"\" class=\"me-1\" />\n");
      out.write("                </button>\n");
      out.write("                <!-- Menu button -->\n");
      out.write("\n");
      out.write("                <!-- Nav Items -->\n");
      out.write("                <div class=\"collapse navbar-collapse align-items-center\" id=\"navbarButtons\">\n");
      out.write("                    <div class=\"me-auto\"></div>\n");
      out.write("                    <!-- <small class=\"text-info me-4\">Link</small> -->\n");
      out.write("                    <ul class=\"align-nav-item\">\n");
      out.write("                        <img src=\"/meetingroommanagement/resources/images/icon_user.png\" height=\"16\" alt=\"\" class=\"me-1\" />\n");
      out.write("                        <small class=\"text-white me-4\">Hi! ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</small>\n");
      out.write("                    </ul>\n");
      out.write("                    <ul class=\"align-nav-item\">\n");
      out.write("                        <a href=\"\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-outline-info\" data-mdb-ripple-color=\"dark\">\n");
      out.write("                                Logout\n");
      out.write("                            </button>\n");
      out.write("                        </a>\n");
      out.write("                    </ul>\n");
      out.write("                    <!-- </div> -->\n");
      out.write("                </div>\n");
      out.write("                <!-- Nav Items -->\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <!-- Navbar -->\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <main id=\"content-wrap\">\n");
      out.write("        <div class=\"container-fluid h-custom\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <section class=\"col-11 col-sm-9 col-md-9 col-lg-5 col-xl-5\">\n");
      out.write("                    <div class=\"d-flex flex-row align-items-center justify-content-center justify-content-lg-start\">\n");
      out.write("                        <p class=\"lead mb-0 mx-3\">Upcoming Meetings</p>\n");
      out.write("                    </div>\n");
      out.write("                    ");
      if (_jspx_meth_e_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </section>\n");
      out.write("                <section class=\"col-11 col-sm-9 col-md-9 col-lg-5 col-xl-5 offset-xl-1 offset-lg-1\">\n");
      out.write("                    <div class=\"d-flex flex-row align-items-center justify-content-center justify-content-lg-start\">\n");
      out.write("                        <p class=\"lead mb-0 mx-3\">Recent Meetings</p>\n");
      out.write("                    </div>\n");
      out.write("                    ");
      if (_jspx_meth_e_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </section>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    <!--Footer-->\n");
      out.write("    <footer id=\"footer\">\n");
      out.write("        <div>\n");
      out.write("            <hr class=\"my-2\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footer-copyright d-flex align-items-center justify-content-center\">\n");
      out.write("            © 2021 Copyright: HSCC Meettings\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("    <!--/.Footer-->\n");
      out.write("\n");
      out.write("    <!--scripts-->\n");
      out.write("    <script src=\"/meetingroommanagement/scripts/scripts.js\"></script>\n");
      out.write("    <!--scripts-->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_e_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_e_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_e_005fforEach_005f0_reused = false;
    try {
      _jspx_th_e_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_e_005fforEach_005f0.setParent(null);
      // /views/member.jsp(73,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_e_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/member.jsp(73,20) '${upcoming}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${upcoming}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /views/member.jsp(73,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_e_005fforEach_005f0.setVar("meeting");
      int[] _jspx_push_body_count_e_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_e_005fforEach_005f0 = _jspx_th_e_005fforEach_005f0.doStartTag();
        if (_jspx_eval_e_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("            			");
            if (_jspx_meth_e_005fset_005f0(_jspx_th_e_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_e_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("	                    <div class=\"card-container\">\n");
            out.write("	                        <div class=\"card-body rounded-4\">\n");
            out.write("	                            <div class=\"row\">\n");
            out.write("	                                <div class=\"col-md-9\">\n");
            out.write("	                                    <h5 class=\"card-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${meeting.meetingTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\n");
            out.write("	                                </div>\n");
            out.write("	                                <div class=\"chip text-center col-md-3 mb-3\">\n");
            out.write("	                                    <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${meeting.timeAsString }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("	                                </div>\n");
            out.write("	                            </div>\n");
            out.write("	                            <div class=\"row\">\n");
            out.write("	                                <div class=\"col-md-7\">\n");
            out.write("	                                    <h6 class=\"card-subtitle text-black\">Organizer</h6>\n");
            out.write("	                                    <p class=\"text-muted\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${meeting.organizedBy}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("	                                </div>\n");
            out.write("	                                <div class=\"col-md-5\">\n");
            out.write("	                                    <h6 class=\"card-subtitle text-black\">Meeting Type</h6>\n");
            out.write("	                                    <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${meeting.meetingType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("	                                </div>\n");
            out.write("	                            </div>\n");
            out.write("	                        </div>\n");
            out.write("	                    </div>\n");
            out.write("	                 ");
            int evalDoAfterBody = _jspx_th_e_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_e_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_e_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_e_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_e_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_e_005fforEach_005f0);
      _jspx_th_e_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_e_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_e_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_e_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_e_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_e_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_e_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fe_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_e_005fset_005f0_reused = false;
    try {
      _jspx_th_e_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_e_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_e_005fforEach_005f0);
      // /views/member.jsp(74,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_e_005fset_005f0.setVar("eid");
      // /views/member.jsp(74,15) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_e_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/views/member.jsp(74,15) '${meeting.meetingTitle}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${meeting.meetingTitle}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_e_005fset_005f0 = _jspx_th_e_005fset_005f0.doStartTag();
      if (_jspx_th_e_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fe_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_e_005fset_005f0);
      _jspx_th_e_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_e_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_e_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_e_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_e_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_e_005fforEach_005f1_reused = false;
    try {
      _jspx_th_e_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_e_005fforEach_005f1.setParent(null);
      // /views/member.jsp(103,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_e_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/views/member.jsp(103,20) '${recent}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${recent}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /views/member.jsp(103,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_e_005fforEach_005f1.setVar("meeting");
      int[] _jspx_push_body_count_e_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_e_005fforEach_005f1 = _jspx_th_e_005fforEach_005f1.doStartTag();
        if (_jspx_eval_e_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                    ");
            if (_jspx_meth_e_005fset_005f1(_jspx_th_e_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_e_005fforEach_005f1))
              return true;
            out.write("\n");
            out.write("	                    <div class=\"card-container\">\n");
            out.write("	                        <div class=\"card-body rounded-4\">\n");
            out.write("	                            <div class=\"row\">\n");
            out.write("	                                <div class=\"col-md-7\">\n");
            out.write("	                                    <h5 class=\"card-title mb-4\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${meeting.meetingTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\n");
            out.write("	                                </div>\n");
            out.write("	                                <div class=\"col-md-5 text-end\">\n");
            out.write("	                                	<a href=\"http://localhost:8080/meetingroommanagement/feedback?room=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${meeting.meetingRoom.meetingRoomId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("		                                    <button type=\"button\" class=\"btn btn btn-outline-primary\">\n");
            out.write("		                                        Rate meeting room\n");
            out.write("		                                    </button>\n");
            out.write("	                                    </a>\n");
            out.write("	                                </div>\n");
            out.write("	                            </div>\n");
            out.write("	                            <div class=\"row\">\n");
            out.write("	                                <div class=\"col-md-7\">\n");
            out.write("	                                    <h6 class=\"card-subtitle text-black\">Organizer</h6>\n");
            out.write("	                                    <p class=\"text-muted\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${meeting.organizedBy}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("	                                </div>\n");
            out.write("	                                <div class=\"col-md-5\">\n");
            out.write("	                                    <h6 class=\"card-subtitle text-black\">Meeting Type</h6>\n");
            out.write("	                                    <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("	                                </div>\n");
            out.write("	                            </div>\n");
            out.write("	                        </div>\n");
            out.write("	                    </div>\n");
            out.write("	                 ");
            int evalDoAfterBody = _jspx_th_e_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_e_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_e_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_e_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_e_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_e_005fforEach_005f1);
      _jspx_th_e_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_e_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_e_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_e_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_e_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_e_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_e_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fe_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_e_005fset_005f1_reused = false;
    try {
      _jspx_th_e_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_e_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_e_005fforEach_005f1);
      // /views/member.jsp(104,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_e_005fset_005f1.setVar("eid");
      // /views/member.jsp(104,20) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_e_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/views/member.jsp(104,20) '${meeting.meetingTitle}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${meeting.meetingTitle}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_e_005fset_005f1 = _jspx_th_e_005fset_005f1.doStartTag();
      if (_jspx_th_e_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fe_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_e_005fset_005f1);
      _jspx_th_e_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_e_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_e_005fset_005f1_reused);
    }
    return false;
  }
}
